trigger:
- 'dev'
- 'master'

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  AWS_REGION: 'sa-east-1'
  AWS_ACCESS_KEY_ID: $(var.aws_access_key)
  AWS_SECRET_ACCESS_KEY: $(var.aws_access_key)

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy'
  steps:

    - script: echo "Building and testing..."
      displayName: 'Build and Test code'

    - checkout: self

    - stage: DeployToDev
      displayName: 'Deploy to Dev'
      jobs:
      - deployment: Deploy
        environment: 'Dev'
        strategy:
          runOnce:
            deploy:
              steps:
              - script: echo "Deploying to Dev..."
                displayName: 'Deploy to Dev'

    - stage: DeployToProd
      displayName: 'Deploy to Production'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      jobs:
      - deployment: Deploy
        environment: 'Production'
        strategy:
          runOnce:
            deploy:
              steps:
              - script: echo "Deploying to Production..."
                displayName: 'Deploy to Production'
